name: sync node
on:
  workflow_call:
  workflow_dispatch:
  push:
  schedule:
  - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update dependence
        run: |
          sudo apt install curl -y
          
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: show date
        run: echo $(date +"%Y/%m/0-%Y%m%d" -d "8 hour")

      - name: download node
        run: |
          curl -o temp.yaml https://www.freeclashnode.com/uploads/$(date +"%Y/%m/0-%Y%m%d" -d "8 hour").yaml
          curl -o temp.txt https://www.freeclashnode.com/uploads/$(date +"%Y/%m/0-%Y%m%d" -d "8 hour").txt
          curl -o temp.json https://www.freeclashnode.com/uploads/$(date +"%Y/%m%Y%m%d" -d "8 hour").json
      - name: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add temp.*
          git commit -a -m "sync node"
          git push
